### ISSUE TITLE
Create a singleton class around the Word Application

### ISSUE THREAD

**Issue by Capm96** [Capm96/Knowledge-Trees#4]
Our leaves are fundamentally word documents. To create word documents in C#, one needs to first have a Microsoft.Office.Interop.Word.Application object, which is essentially an instance of Word in which we can add/save documents.

Creating such instance is straight forward, we simply call: `            var wordInstance = new Application();`

However, there are a few issues with doing so. 

1. Creating new instances repeatedly is not so quick -- there is a delay of a few seconds which can be taxing to the user.
2. Getting rid of word instances is not so simple too, and might cause errors down the line.

A better idea would be to create a wrapper class around this word instance, which gets built the first time the application is run. Then, any point in our code which depends on a Word application, like the code piece above, should instead just look to this singleton class.

When the application is closed, the Word instance should be disposed appropriately.

**Comment by ghost** [comment]
Hi Capm96, I'd like to help with this issue.

**Comment by Capm96** [comment]
Hey @pdelco thanks a lot for the interest! Will assign this issue to you 👍
